// Events can also be generated by specifying a **range** and the events to
// generate within that range.
package main

import (
	"fmt"

	"github.com/shasderias/ilysa"
	"github.com/shasderias/ilysa/beatsaber"
	"github.com/shasderias/ilysa/context"
	"github.com/shasderias/ilysa/ease"
	"github.com/shasderias/ilysa/evt"
	"github.com/shasderias/ilysa/timer"
)

func main() {
	m, _ := beatsaber.NewMockMap(beatsaber.EnvironmentOrigins, 120, "[]")
	p := ilysa.New(m)

	// Generate events starting from beat 0 and ending on beat 0.5 a total of 6 times.
	p.Range(timer.Rng(0, 0.5, 6, ease.Linear), func(ctx context.Context) {
		ctx.NewLighting(
			evt.WithLight(evt.BackLasers),
			evt.WithLightValue(evt.LightBlueFade),
		)

		// The values available on a **sequence**'s context are also available on
		// on a **range**'s context.
		fmt.Printf("%4.2f %4.2f %1d %4.2f %t\n",
			ctx.B(), ctx.T(), ctx.Ordinal(), ctx.SeqNextBOffset(), ctx.Last())
	})

	p.Dump()
}
